name: "rent_a_car_v2"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      - selenium
      - redis
      - postgres
    ports:
      - "3000:3000"

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"

  redis:
    image: redis:7.2
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  redis-data:
  postgres-data:
  minio-data:
